[package]
name = "typetune-tray"
version.workspace = true
edition.workspace = true

[dependencies]
typetune-core = { path = "../typetune-core" }
typetune-config = { path = "../typetune-config" }
ksni = "0.2"
tracing = "0.1"
zbus = { version = "3", default-features = false, features = ["tokio"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
libc = "0.2"
