#!/bin/bash
set -e

case "$1" in
    remove|upgrade)
        systemctl --user stop typetune.service 2>/dev/null || true
        systemctl --user disable typetune.service 2>/dev/null || true
        ;;
esac
