[package]
name = "typetune-helper"
version.workspace = true
edition.workspace = true

[dependencies]
typetune-input = { path = "../typetune-input" }
typetune-inject = { path = "../typetune-inject" }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
libc = "0.2"
signal-hook = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
